name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  main:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SKIP_ASSETS : true
        IGNORE_OTHER_FILES: true
        SLUG: automatic-cache-flusher-for-w3-total-cache
        
